- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  GOD MODE (ep. 1)
  url:    https://example.com
- title:  ECHO FX
  url:    https://example.com
- title:  ECHO FX
  url:    https://example.com
- title:  ECHO FX
  url:    https://example.com
- title:  ECHO FX
  url:    https://example.com
- title:  ECHO FX
  url:    https://example.com
- title:  ECHO FX (Krisis Publishing, 2021)
  url:    https://example.com
- title:  ECHO FX (Krisis Publishing, 2021)
  url:    https://example.com
- title:  ECHO FX (Krisis Publishing, 2021)
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  INTERFACE CHAOS
  url:    https://example.com
- title:  A CHAOS OF INTERFACES
  url:    https://example.com
- title:  A CHAOS OF INTERFACES
  url:    https://example.com
- title:  OFFSHORESS18
  url:    https://example.com
- title:  OFFSHORESS18
  url:    https://example.com
- title:  OFFSHORESS18
  url:    https://example.com
- title:  OFFSHORESS18
  url:    https://example.com
- title:  OFFSHORESS18
  url:    https://example.com
- title:  Offshore Investigation Vehicle
  url:    https://example.com
- title:  Offshore Investigation Vehicle
  url:    https://example.com
- title:  Offshore Investigation Vehicle
  url:    https://example.com
- title:  Offshore Investigation Vehicle
  url:    https://example.com
- title:  Offshore Investigation Vehicle
  url:    https://example.com
- title:  The Offshore Economist
  url:    https://example.com
- title:  The Offshore Economist
  url:    https://example.com
- title:  The Offshore Economist
  url:    https://example.com
- title:  The Offshore Economist
  url:    https://example.com
- title:  The Offshore Economist
  url:    https://example.com
- title:  Offshore A–Z
  url:    https://example.com
- title:  Offshore A–Z
  url:    https://example.com
- title:  Flash Demons
  url:    https://example.com
- title:  Network Studies I, VII, VIII
  url:    https://example.com
- title:  Network Studies I, VII, VIII
  url:    https://example.com
- title:  Network Studies I, VII, VIII
  url:    https://example.com
- title:  Selected Network Studies
  url:    https://example.com
- title:  NEX
  url:    https://example.com
- title:  NE3
  url:    https://example.com